server.port=8181

spring.application.name=Devantrum


spring.datasource.url=jdbc:postgresql://localhost:5432/devantrum
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect